# Generated by Django 4.2 on 2025-06-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perbandinganalternatif',
            name='alternatif_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt1', to='accounts.penggunaanbelanja'),
        ),
        migrations.AlterField(
            model_name='perbandinganalternatif',
            name='alternatif_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt2', to='accounts.penggunaanbelanja'),
        ),
        migrations.DeleteModel(
            name='Alternatif',
        ),
    ]
