# Generated by Django 4.2 on 2025-06-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bidang',
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='bidang',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Bidang',
        ),
    ]
