# Generated by Django 4.2 on 2025-06-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_bidang_alter_kegiatan_bidang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bidang',
            field=models.CharField(blank=True, choices=[('bina_konstruksi', 'Bina Konstruksi'), ('sumber_daya_air', 'Sumber Daya Air'), ('penataan_ruang', 'Penataan Ruang'), ('keuangan', 'Keuangan'), ('umum_kepegawaian', 'Umum & Kepegawaian'), ('program_cipta_karya', 'Program Cipta Karya'), ('binta_marga', 'Binta Marga'), ('upt_air_minum', 'UPT Air Minum')], max_length=50, null=True),
        ),
    ]
