# Generated by Django 4.2 on 2025-06-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_perbandinganalternatif_alternatif_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersetujuanPenggunaanBelanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penggunaan_belanja_id', models.IntegerField()),
                ('nama_penggunaan', models.CharField(max_length=200)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=14)),
                ('kode_rekening', models.CharField(max_length=20)),
                ('nama_rekening', models.CharField(max_length=100)),
                ('kode_sub_kegiatan', models.CharField(max_length=20)),
                ('nama_sub_kegiatan', models.CharField(max_length=100)),
                ('kode_kegiatan', models.CharField(max_length=20)),
                ('nama_kegiatan', models.CharField(max_length=100)),
                ('bidang', models.CharField(max_length=100)),
                ('disetujui', models.BooleanField(default=False)),
                ('ditolak', models.BooleanField(default=False)),
                ('tanggal_persetujuan', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
