# Generated by Django 4.2 on 2025-06-14 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_persetujuanpenggunaanbelanja'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='disetujui', max_length=20)),
                ('tanggal_persetujuan', models.DateTimeField(default=django.utils.timezone.now)),
                ('penggunaan_belanja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpa_entries', to='accounts.penggunaanbelanja')),
            ],
        ),
    ]
