# Generated by Django 4.2 on 2025-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_bidang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='bidang',
            field=models.CharField(choices=[('bina_konstruksi', 'Bina Konstruksi'), ('sumber_daya_air', 'Sumber Daya Air'), ('penataan_ruang', 'Penataan Ruang'), ('keuangan', 'Keuangan'), ('umum_kepegawaian', 'Umum & Kepegawaian'), ('program_cipta_karya', 'Program Cipta Karya'), ('binta_marga', 'Binta Marga'), ('upt_air_minum', 'UPT Air Minum')], max_length=50),
        ),
    ]
