# Generated by Django 4.2 on 2025-06-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_kegiatan_bidang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegiatan',
            name='kode_rekening',
        ),
        migrations.RemoveField(
            model_name='kegiatan',
            name='kode_sub_kegiatan',
        ),
        migrations.RemoveField(
            model_name='kegiatan',
            name='nama_rekening',
        ),
        migrations.RemoveField(
            model_name='kegiatan',
            name='nama_sub_kegiatan',
        ),
        migrations.CreateModel(
            name='SubKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_sub_kegiatan', models.CharField(max_length=20)),
                ('nama_sub_kegiatan', models.CharField(max_length=100)),
                ('kode_rekening', models.CharField(max_length=20)),
                ('nama_rekening', models.CharField(max_length=100)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_kegiatan', to='accounts.kegiatan')),
            ],
        ),
    ]
