# Generated by Django 4.2 on 2025-06-07 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_kegiatan_kode_rekening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subkegiatan',
            name='kode_rekening',
        ),
        migrations.RemoveField(
            model_name='subkegiatan',
            name='nama_rekening',
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='kode_kegiatan',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subkegiatan',
            name='kegiatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_kegiatans', to='accounts.kegiatan'),
        ),
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_rekening', models.CharField(max_length=20)),
                ('nama_rekening', models.CharField(max_length=100)),
                ('sub_kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekenings', to='accounts.subkegiatan')),
            ],
        ),
    ]
