# Generated by Django 4.2 on 2025-06-08 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_subkegiatan_kode_rekening_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenggunaanBelanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penggunaan', models.CharField(max_length=200)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rekening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penggunaan_belanjas', to='accounts.rekening')),
            ],
        ),
    ]
