# Generated by Django 4.2 on 2025-06-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_penggunaanbelanja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrioritasKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot', models.DecimalField(decimal_places=4, max_digits=6)),
                ('kriteria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.kriteria')),
            ],
        ),
        migrations.CreateModel(
            name='PerbandinganKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=4)),
                ('kriteria_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perbandingan_kriteria_1', to='accounts.kriteria')),
                ('kriteria_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perbandingan_kriteria_2', to='accounts.kriteria')),
            ],
            options={
                'unique_together': {('kriteria_1', 'kriteria_2')},
            },
        ),
    ]
