# Generated by Django 4.2 on 2025-06-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_kriteria_prioritaskriteria_perbandingankriteria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='perbandingankriteria',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perbandingankriteria',
            name='nilai',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='PrioritasKriteria',
        ),
    ]
