# Generated by Django 5.2.3 on 2025-06-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_perbandingankriteria_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobotKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_bobot', models.FloatField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kriteria')),
            ],
        ),
    ]
