# Generated by Django 5.2.3 on 2025-06-12 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bobotkriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penggunaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.penggunaanbelanja')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiAlternatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_alternatif', to='accounts.alternatif')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kriteria')),
            ],
        ),
    ]
