# Generated by Django 5.2.3 on 2025-06-12 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alternatif_nilaialternatif'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerbandinganAlternatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('alternatif_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatif1', to='accounts.alternatif')),
                ('alternatif_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatif2', to='accounts.alternatif')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kriteria')),
            ],
        ),
        migrations.DeleteModel(
            name='NilaiAlternatif',
        ),
    ]
